### ISSUE TITLE
Webpack not found

### ISSUE THREAD

**Issue by pussyLexispussy** [Ceiridge/SimpleDiscordCrypt-Extended#5]
originalLogFn.apply(this, arguments); 

theres where the error is , i tried installing betterdiscord but still doesnt work ;(

**Comment by Ceiridge** [comment]
How did you install SimpleDiscordCrypt? Have you used the powershell installer?

**Comment by pussyLexispussy** [comment]
yeah

**Comment by Ceiridge** [comment]
To investigate this, I would need more details about the error, maybe stacktraces and line numbers. The code you have given me does not appear anywhere in SDCEx

**Comment by pussyLexispussy** [comment]
works with normal discord but not for discord canary

**Comment by Ceiridge** [comment]
Discord Canary is not supported

**Comment by pussyLexispussy** [comment]
oh i see my bad
