### ISSUE TITLE
"Webpack not found." on Discord Stable with BetterDiscord

### ISSUE THREAD

**Issue by SourCandy80** [Ceiridge/SimpleDiscordCrypt-Extended#7]
![image](https://github.com/Ceiridge/SimpleDiscordCrypt-Extended/assets/111071796/ea4d83e1-1847-45ea-a39a-8e84ea0fcbf8)

**Comment by Ceiridge** [comment]
Please redirect this issue to https://gitlab.com/An0/SimpleDiscordCrypt
This is only a fork of that original repository, which adds some features
